### ISSUE TITLE
build instructions

### ISSUE THREAD

**Issue by raymiec** [ffpetrovic/aubio-android-pitch-test#1]
Can you help me get this build, i've tried numerous ways and just keep getting errors, if you have any build instructions that would be appreciated.  Cheers

**Comment by ffpetrovic** [comment]
Hey @raymiec, unfortunately, I've never managed to get it working ( at least not in a Windows environment ), but I managed but piem pointed me to a link where the most recent build of the libraries for android are 
https://aubio.org/bin/android/0.4.7~git+3a8f0bf/ 
If you need something more specific it may be best to open an issue on their repo

Hope this helped :)

**Comment by ffpetrovic** [comment]
Are you actually trying to build for some specific platform that they didn't include? 
I'm just using this config for Android.mk

```
LOCAL_PATH := $(call my-dir)

include $(CLEAR_VARS)

include $(CLEAR_VARS)
LOCAL_MODULE := aubio
LOCAL_SRC_FILES := $(TARGET_ARCH_ABI)/libaubio.so
LOCAL_EXPORT_C_INCLUDES := $(LOCAL_PATH)/include
include $(PREBUILT_SHARED_LIBRARY)

include $(CLEAR_VARS)
LOCAL_MODULE := pitch
LOCAL_SRC_FILES := pitch.c
LOCAL_SHARED_LIBRARIES := aubio
include $(BUILD_SHARED_LIBRARY)
```

and in that same directory I have all the appropriate platforms that I took from those zip files, and the `includes` folder I literally just pasted the entire source of the library ( although you just need the header files and not `.c` files ). Let me know if this part is something you need help with, I can provide more details because I've been using the library for an Android project for a while now and it's been going great

**Comment by raymiec** [comment]
I'm basically just trying to get an android app running lol,  i have a python source i'm trying to port over, i did get an example working but it got all weird.  I'm not bad with java but i've never actually built anything externally with it using cmake etc.

Have you got a better example project maybe that i could just compile out the box sort of thing?

**Comment by ffpetrovic** [comment]
An Android project that uses the **prebuilt** aubio library? If yes, then I will try to get one ready for you in a couple of days

**Comment by raymiec** [comment]
Nice one, i'll even buy you a few beers.

**Comment by ffpetrovic** [comment]
Actually, give me a few tens of minutes, I think I can come up with something

**Comment by ffpetrovic** [comment]
Okay well look, I managed to get this example running on my phone, so I think that's "out of the box" enough 😂
Please don't mind the **entire project typo**, the C code mess, the app permissions mess etc... I'm sure you can figure all of those out with a google search

Anyway, here's the repo: https://github.com/ffpetrovic/android-aubio-example

**Comment by ffpetrovic** [comment]
Well that's weird, any error or something? Does the text on the TextView not change?  You granted permissions?

**Comment by raymiec** [comment]
yeah granted permission and restarted the app, nothing changes on the textview.  I'm on android p, think its audio related issues, i'll look into it further now, literally just browsing the code and working out whats what.

**Comment by raymiec** [comment]
cleared cache etc, seems to work fine now, the main error was AudioRecord: start() status -38.

**Comment by ffpetrovic** [comment]
Glad it helped, don't forget to refer anyone who doesn't know how to use aubio on Android to this repo, I wasted so much time on this problem, hopefully it'll help someone

**Comment by raymiec** [comment]
Don't worry i will, and i'll also credit you and link back to the projects from my projects!  just tested it out as well, even from that example its accurate as hell as a guitar tuner!

Can also submit PR for other examples to add once i've done a bit of work if you like.

**Comment by valnenov** [comment]
Hi guys, I was able to successfully incorporate Filip's aubio pitch example for android in my android app, but I am having hard time making further progress. Specifically, I want to use the beat detection functions of aubio (e.g. new_fvec new_aubio_tempo aubio_tempo_set_silence new_aubio_source aubio_source_do, etc). I was able to use them successfully in an iOS project. Do you have any suggestions on how to go about it?  Is there a pitch.c-like file for tempo and beats detection? I asked Piem for help but haven't heard back from him. Any pointers and code examples will be greatly appreciated. 

On a side note, I have still not figured out how to load/link the static libaubio.a into my Android studio app. Perhaps if I succeed in doing that I will be able to import or link it and see all the methods I need. Any suggestions?

Thanks, 
Val

**Comment by ffpetrovic** [comment]
Hey Val,

I will try to get to your issue in terms of how I went about importing aubio into a project,
But in the meantime, please check my "auxilium" repo, clone it and see if the project even compiles. If it does, you can maybe use that as a template, because if I remember correctly, the whole library is added there, including tempo detection.

I will try to get back to you soon on how to make a pitch.c like file for your needs

Good luck 🙂

**Comment by valnenov** [comment]
Thank you Filip for the prompt reply. I will take a look at the auxilium
repo.

Best regards,
Val

**Comment by valnenov** [comment]
Hi Filip,

thank you so much for pointing me in the right direction. I downloaded,
compiled and installed Auxilium on my Huawei Mate 20 phone and it works
great. Looks like a very sophisticated app and is very much in the music
domain, which is of great interest to me too. Will study it closely and
will see if I can use it as a basis for beat detection in my SK8AR app.

Here just for kicks are a couple of links, which I posted just yesterday
that show the stuff that I am working on.
https://www.facebook.com/204831997049407/videos/258527831756746/
https://www.facebook.com/Sk8SoniXVal/videos/369349630586238/

Will let you know when I make some progress with Aubio.

Val

**Comment by valnenov** [comment]
Hi Filip,
me again:-) OK, I see that you are loading the aubio and pitch modules in
your Tuner.java file. I also see that you have the libaubio.so and
libaubio.a for all targets in your jni folder, but I don't see you using
them explicitly except the libaubio.so in your Android.mk. Am I missing
something? How do I generate a pitch.c - like "wrapper" for the
tempo/beatsdetection so I can make a tempo module? Is there a way to
"import aubio" like it is done in iOS (obj-c, swift)?

Val

**Comment by valnenov** [comment]
Hi Filip,

I am so sorry to bother you again, but was just wondering, do you happen to
have any additional feedback on my issue.
Thanks so much for your help.

Val

**Comment by ffpetrovic** [comment]
Hey Val,

Can you tell me exactly what problem you're having?
The `pitch.c` file is not generated per se, I wrote it. You can read the aubio docs to find out how to use beat/tempo detection or something else you want to use from the library.

1. In terms of function naming ( the `Java_com_xxx....` ), you can google to see how that naming works, but I'm pretty sure you can figure it out just by looking at it, and yes, it's important.
2. Include jni.h and aubio.h like I did in my `pitch.c` file and write the functions you need. When you try to compile, the compiler should tell you which headers you're missing, so include them. 
3. Don't forget the first few `getXXXFieldId`, those are important as well.

All of this you can find out on google, the only thing you should take from my example, is how you include aubio into your `.c` file. I'm not sure how it's done on iOS, but here the process is as you can see;
Make a `.c` script that includes aubio from it's source, and write the aubio usage functions inside that script. After that, call

```
static {
        System.loadLibrary("aubio");
        System.loadLibrary("pitch");
}
```
like I did, in `Tuner.java` and don't to declare the native methods in that same file, e.g.
```
private native float    getPitch(float[] input);
private native void     initPitch(int sampleRate, int B);
private native void     cleanupPitch();
```

And just call these methods from that `.java` file.

For storing variables between C and Java ( JNI ), those `getXXXFieldId` methods are used.

90% of the stuff I wrote can be found out with 10 minutes of googling. The only issue I had, the only issue that's not documented anywhere, and the reason I created the repo, is because I didn't know how to properly add this library to a project. And I did that through that `Android.mk` file to compile the library into the project, the `pitch.c` file to include and use the library into a C script, and with `Tuner.java` to call the functions from that C script.

Hope it's clearer now

**Comment by valnenov** [comment]
Hi Filip,

thank you so much for your generous help.
I decided that since I already were able to successfully incorporate your
pitch code into my app the simplest ways was to add an extra function in
your pitch.c file which does the beats detection. Fortunately I was able to
see all aubio functions and variable types that I need in the pitch.c. All
I needed to do was:
   1) Open a resource .mp3 file from R.raw.mySong.mp3
   2) Translate the aubio functions that I already was successfully using
in my iOS project from swift to c.
   3) Compile and run.

Below is the _getBeats function that I wrote:

// Val modified from above Filip's getPitch
jfloatArray Java_com_google_ar_sceneform_samples_drawing_DrawingActivity_getBeats(JNIEnv
* env, jobject obj, jint sampleRate, jint path)
{

    char_t *path1 = (char_t *) (*env)->GetLongField(env, obj,
getPathFieldId(env, obj));

    uint_t sampleSize = 128;
    fvec_t * samples = new_fvec(sampleSize);
    aubio_tempo_t * tempo = new_aubio_tempo("default", 1024,
sampleSize, (uint_t) sampleRate);

    float silenceThreshold = -40.0f;
    aubio_tempo_set_silence(tempo, silenceThreshold);

    // next
    aubio_source_t * source = new_aubio_source(path1, 0, sampleSize);
    fvec_t * out = new_fvec(1);
    uint_t read = 0;
    uint_t total_frames = 0;
    unsigned int beatCount = 0;

    // Create a big enough array assuming that there are no more than
200 beats in the song
    int beatsMax = 200;
    jfloatArray beats[beatsMax]; // assume that there are 200 beats
MAX in the song

    // Create an array in JNI
    // per answer 2 in
https://stackoverflow.com/questions/25011597/convert-float-to-jfloatarray-using-jni
    jfloatArray result;
    result = (*env)->NewFloatArray(env, beatsMax);

    float* data;
    data = malloc(sizeof(float) * beatsMax);

    int i = 0; // this is the current position in the array

    do {
        aubio_source_do(source, samples, &read );
        total_frames += read;
        beatCount = beatCount + 1;
        aubio_tempo_do(tempo, samples, out);

        // Populate the data array with the beat_times
        if (fvec_get_sample(out, 0) != 0) {
            float beat_time = (float)total_frames / (float)sampleRate;

            if (i < beatsMax) data[i++] = beat_time;// beats[i++] =
beat_time; // adds beat_time in position i
        }

    } while( false );

//    // just for testing: set the first 4 values of result
//    data[0] = 0.0f; data[1] = 1.1f; data[2] = 2.2f; data[3] = 3.3f;
//    int beatsCount = 4;

    jfloatArray resultTrimmed;
    resultTrimmed = (*env)->NewFloatArray(env, beatCount);

    float* dataTrimmed;
    dataTrimmed = malloc(sizeof(float) * beatCount);

    // copy the first beatsCount elements of data to dataTrimmed
    for(int j = 0; j < beatsMax; j++) {
        if (j < beatCount) {dataTrimmed[j] = data[j];}
    }

    (*env)->SetFloatArrayRegion(env, result, 0, beatsMax, data);
    free(data);

    (*env)->SetFloatArrayRegion(env, resultTrimmed, 0, beatCount, dataTrimmed);
    free(dataTrimmed);

    return resultTrimmed;

}


I also added to the top of the pitch.c:

// Val added modeled on the above
jfieldID getPathFieldId(JNIEnv * env, jobject obj)
{
    static jfieldID ptrFieldId = 0;

    if (!ptrFieldId)
    {
        jclass c = (*env)->GetObjectClass(env, obj);
        ptrFieldId = (*env)->GetFieldID(env, c, "path", "J");
        (*env)->DeleteLocalRef(env, c);
    }

    return ptrFieldId;
}

and in my java file I call the _getBeats function as follows:

int path = getResources().getIdentifier("mySong","raw","com.google.ar.sceneform.samples.drawing");
// mySong is mySong.mp3 in R.raw

float[] beatsArray = getBeats(samplerate,path);

and also I have:

private native float    getPitch(float[] input);
private native void     initPitch(int sampleRate, int B);
private native void     cleanupPitch();

// Val added
private native float[]    getBeats(int sampleRate, int path);


my PROBLEM: Apparently I am not providing the path to the mp3
correctly and it crashes.

I tried to get some examples of how to do that from How to Call Kotlin
from Native Code Using Android NDK - Yalantishttps://yalantis.com ›
Blog › Tech <https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=5&cad=rja&uact=8&ved=2ahUKEwjir6iio5ThAhXSv54KHRLNCKsQFjAEegQIARAB&url=https%3A%2F%2Fyalantis.com%2Fblog%2Fandroid-ndk-calling-kotlin-from-native-code%2F&usg=AOvVaw2K1ozcElvJYVfHAw26DHxh>
but could not figure it out.

Can you please help one more time?


Best regards,


Val

**Comment by valnenov** [comment]
Hi Filip,
I am really sorry to bug you again. I spent most of the weekend trying to
open mp3 files from the pitch.c module but no luck. Tried variety of
options including using AAssetManager but still was not able to provide the
correct file_pointer/file_path for the assetfilename in the following call :

aubio_source_t * source = new_aubio_source(assetfilename, 0, sampleSize);
// and

aubio_source_do(source, samples, &read );

Do you have any suggestion on how to do that? I have ran out of options.
Thank you!!!

Val

**Comment by ffpetrovic** [comment]
Hey @valnenov ,

Honestly, this seems somewhat outside of my area, have you tried opening an issue about it on the aubio repo?

**Comment by valnenov** [comment]
Thanks for your prompt reply Filip. I haven’t opened an issue yet on aubio
but I will. Appreciate your help and sorry again for bugging you.
Best regards,
Val
